Prevent deletion
SAP/sap-btp-service-operator pull request #315
Opened 2023-08-02 12:38 UTC by TalShorSap

Prevent deletion flag on instance spec

2023-08-02 13:32 UTC, kerenlahav requested changes

2023-08-02 13:32 UTC, kerenlahav commented on api/v1/serviceinstance_types.go
> +	PreventDeletion bool `json:"prevent_deletion"`
should be an annotation and not part of the spec

2023-08-02 13:32 UTC, kerenlahav commented on api/v1alpha1/serviceinstance_types.go
> +	PreventDeletion bool `json:"prevent_deletion"`
not relevant

2023-08-02 13:32 UTC, kerenlahav commented on api/v1/serviceinstance_types.go
> +// +kubebuilder:printcolumn:JSONPath=".spec.preventDeletion",name="PreventDeletion",type=boolean
remove

2023-08-03 06:17 UTC, kerenlahav commented on api/v1/serviceinstance_validating_webhook.go
> +		if _, ok := si.Annotations[api.PreventDeletion]; ok {
what if iset
"services.cloud.sap.com/preventDeletion": "false" ?

2023-08-03 07:37 UTC, TalShorSap commented on api/v1/serviceinstance_validating_webhook.go
> +		if _, ok := si.Annotations[api.PreventDeletion]; ok {
fixed

2023-08-08 12:45 UTC, kerenlahav approved these changes

2023-08-08 12:48 UTC, merged